local COLORS = {
	vmath.vector4(0.2, 0.9, 0.4, 0),
	vmath.vector4(0.2, 0.3, 1, 0),
	vmath.vector4(1, 1, 1, 0),
	vmath.vector4(0.5, 0.2, 1, 0)
}

function init(self)
	self.color = COLORS[math.random(1, #COLORS)]
	self.time = math.random(0, 200)
	model.set_constant("starnest#model", "color", self.color)
end

function update(self, dt)
	self.time = self.time + dt
	model.set_constant("starnest#model", "time", vmath.vector4(self.time, 0, 0, 0))
end